### ISSUE TITLE
FROG genuine registry is missing

### ISSUE THREAD

**Issue by perlisweird** [FROG-TIPS/frog_gopher#3]
We urgently need to be able to search for genuine FROG identification numbers at `GOPHER://GOPHER.FROG.TIPS/GENUINE` (note the domain is `GOPHER.FROG.TIPS` not just `FROG.TIPS`)

See: https://github.com/FROG-TIPS/frog.tips/issues/11

**Comment by perlisweird** [comment]
@zgrep please evaluate if this meets the community's needs

**Comment by perlisweird** [comment]
Fixed in 67be965f8a076c6d87fac100bf93f6b1a21d131a

**Comment by zgrep** [comment]
After extensive validation over a series of two-hundred and thirty four gruelingly long days, putting the gopher through its paces, we have successfully eradicated all non-genuine FROGs from our collection.

The gopher has been found to be rusty at times, and therefore we request that you polish the gopher more thoroughly. Metal gophers are quaint, and we believe out of style, but that is your stylistic decision to make.

Additionally, we seem to be out of FROGs. Could you please send us some? Thank you.

**Comment by perlisweird** [comment]
Yes we are currently working on the SSL error. I hate it so much it's awful and coarse and gets everywhere in the mainframe.

Please leave your Berkeley room number so that we may send you additional FROGs thank you.
